engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  pep8:
    enabled: true

ratings:
  paths:
  - "**.py"

exclude_paths:
- test/
- nn/
- rl/run_gym_tour.py
- rl/__init__.py